### PR TITLE
Batch disposition calls return nil rather than 0 value

### LINKED ISSUE #145: batch disposition doUpdate returns unexpected result
When calling `SendBatchDisposition` [here](https://github.com/Azure/azure-service-bus-go/blob/master/entity.go#L207)

It uses `doUpdate` [here](https://github.com/Azure/azure-service-bus-go/blob/master/batch_disposition.go#L69)

The issue is that a zero value is returned for the error, which isn't expected behavior in go.

For a calling function that operates normally you can expect this code

```golang
err := s.SendBatchDisposition(ctx, iter)
if err != nil {
    return fmt.Errorf("unable to update dispostion:  %v", err)
}

//do more stuff
```

The current implementation will never get to the `//do more stuff` section.

### PR DESCRIPTION
**Pull request by JakeBjorke**
Current implementation does not have a way [`SendBatchDisposition`](https://github.com/Azure/azure-service-bus-go/blob/master/entity.go#L207) won't return a `nil` error.

Switching to a pointer allows the use of `var` and adding a `nil` check before using `new` to create the object.

Another option was modifying `SendBatchDisposition` to check the length of the internal error collection of the `BatchIteratorError` but that did not seen correct.

Fixes #145

### CODE REVIEW

**Comment by JakeBjorke** [comment]
Any chance someone cal take a look at this? @devigned ?

**Comment by devigned** [comment]
@JakeBjorke I've been hesitant to give it a look since I've transitioned to another team and have have transitioned the maintenance and future development of this project to @gavinfish and @jhendrixMSFT. If they are not able to take a resolve this issue, I'll take a look in my spare time.

Also, if you want to propose a PR, I'll gladly review it. I think it should be a relatively benign change.

**Comment by JakeBjorke** [comment]
@devigned this is the PR that I have proposed.

**Comment by devigned** [comment]
:( -- not enough coffee this morning

**Comment by devigned** [comment]
lgtm!

**Pull request merged**
