### PR TITLE
tell users they can't go higher than 5 minutes

### PR DESCRIPTION
**Pull request by paulgmiller**
Today if you pass SubscriptionWithLockDuration a duration > 5 minutes you will just never get messages. 
Here I am attempting to fail faster.
Another alternative would be to have the put fail.

### CODE REVIEW

**Review by xhl873 — APPROVED** [review]

**Review by charliedmcb — APPROVED** [review]
LGTM

**Review by blaquezzz — APPROVED** [review]

**Comment by serbrech** [comment]
ping @jhendrixMSFT

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
Could you update the version in `namespace.go` please?  It should be `v0.10.9`.  I'll then merge and tag.

**Comment by paulgmiller** [comment]
@jhendrixMSFT  thanks pushed.

**Review by jhendrixMSFT — APPROVED** [review]

**Pull request merged**
