### PR TITLE
Propagate amqp.Message.Ignore() to servicebus.Message

### PR DESCRIPTION
**Pull request by orzel7**

### CODE REVIEW

**Review by wregen — APPROVED** [review]

**Comment by serbrech** [comment]
Hi, thanks for your contribution.
What is your use case to call Ignore() instead of Complete()?

**Comment by orzel7** [comment]
Obviously, in case when i want just ignore message and **unblock** message pump to be able to receive next message. Unblock is a key here.

**Comment by serbrech** [comment]
I understand that, but Ignore does the same conceptually as Complete. why can't you call Complete?

**Comment by orzel7** [comment]
Yes, exactly. For example if some processing fails, i want to give a second chance after peek lock expiration. Another case - under some conditions(i am going to create separate issue with example) Complete() call may hang. As workaround, i am using REST API to complete the message in pair with Ignore() to unlock message pump.

**Comment by devigned** [comment]
@orzel, using the REST API to complete the message due to `Complete()` hanging is clever, but is also concerning for multiple reasons. `Complete()` should not hang, and if it does, it is a bug and should be corrected.

**Comment by serbrech** [comment]
if you want to retry the message. Abandon is the right way to go.
As David says, Complete should never hang, and there isn't any reason to use the rest api to call Complete instead.

I can see how Ignore can be useful to implement a "retry later" pattern, using the peek lock timeout as the interval, but I'm not sure if I want to encourage that by exposing it.
I'd want to check if the other ServiceBus SDK expose it as well.

**Comment by orzel7** [comment]
In case of Qpid Proton library, API exposes functionality to manually control flow.

**Comment by serbrech** [comment]
Qpid is an amqp library. The equivalent would be Azure/go-amqp

**Comment by orzel7** [comment]
@devigned , please see #221

**Comment by serbrech** [comment]
replied on #221 Thanks @orzel7 for hanging around :)

**Pull request closed without merging**
