### PR TITLE
Moving Examples

### PR DESCRIPTION
**Pull request by marstr**
I've updated the scheduledMessages example so that it'll show up in GoDoc and run as a unit test. If you like this pattern, I'll do the same with the rest of the `_example` directory.

### CODE REVIEW

**Comment by devigned** [comment]
I'm all for doing the same with the examples directory. Thank you, @marstr!

**Comment by marstr** [comment]
Everything should now be good to go!

One note, I ended up duplicating some code so that each individual sample was fairly self-contained.

**Comment by devigned** [comment]
@marstr looks like the build is currently failing.

**Comment by marstr** [comment]
All over it :)

**Pull request merged**
