### PR TITLE
fix receiver.Listen goroutine leak issue

### PR DESCRIPTION
**Pull request by mcgradycchen**
Relate issue #104

### CODE REVIEW

**Comment by devigned** [comment]
Awesome find! Thank you.

I want to run this through some tests, but should be able to get this pulled in quickly.

**Comment by devigned** [comment]
What do you think about the following for use in `listenForMessages`. I think this will achieve the same goal.

```go
for {
	msg, err := r.listenForMessage(ctx)
	if err == nil {
		// pass message on or close due to context cancellation
		select {
		case <-ctx.Done():
			return
		case msgChan <- msg:
		}
	} else {
		// handle recovery
	}
}
```

**Comment by mcgradycchen** [comment]
@devigned  the new listenForMessages will have two problems.

Firstly, check `ctx.Done` before push `msg` to `msgChan` is much better than before. But, in some very very very extremely situation, it still has race condition theoretically. 

Second, it will caused a pulled message not be handled immediately. It has to wait for lock expired and will be delivered again.

So, I think loop with `for range chan`, and close it after ctx expired is more suitable.

**Comment by devigned** [comment]
I agree with your reasoning. Thank you for the PR and discussion. I'll get this merged.

**Pull request merged**
